// Baza haseł IMPOSTOR — pary [hasło, bliźniak] do wariantu "bliźniacze hasło".
// W trybie zwykłym losowana jest jedna strona pary.
export const FAMILY = [
{id:'zwierzeta',name:'Zwierzęta',words:[
["żyrafa","struś"],["pingwin","foka"],["jeż","kret"],["słoń","mamut"],["kot","pies"],
["chomik","świnka morska"],["papuga","kanarek"],["rekin","delfin"],["żółw","ślimak"],["lew","tygrys"],
["wilk","lis"],["niedźwiedź","łoś"],["koń","osioł"],["krowa","koza"],["kura","kaczka"],
["sowa","nietoperz"],["pszczoła","osa"],["komar","mucha"],["pająk","skorpion"],["wąż","jaszczurka"],
["żaba","ropucha"],["bocian","żuraw"],["wiewiórka","szop pracz"],["mrówka","żuk"],["motyl","ćma"],
["orzeł","sokół"],["flaming","paw"],["wielbłąd","lama"],["kangur","koala"],["małpa","goryl"],
["krokodyl","aligator"],["hipopotam","nosorożec"],["zebra","antylopa"],["panda","leniwiec"],["jednorożec","pegaz"],
["dinozaur","smok"],["złota rybka","karp"],["homar","krab"],["ośmiornica","meduza"],["jamnik","mops"]]},
{id:'jedzenie',name:'Jedzenie',words:[
["pierogi","uszka"],["pizza hawajska","zapiekanka"],["żurek","barszcz biały"],["kebab","gyros"],["schabowy","kotlet mielony"],
["bigos","kapuśniak"],["rosół","krupnik"],["naleśniki","racuchy"],["placki ziemniaczane","pyzy"],["spaghetti","lasagne"],
["sushi","ramen"],["hamburger","hot dog"],["frytki","chipsy"],["lody","sorbet"],["sernik","szarlotka"],
["pączek","drożdżówka"],["gofry","churros"],["czekolada","krem czekoladowy"],["żelki","guma do żucia"],["popcorn","nachosy"],
["ogórek kiszony","kapusta kiszona"],["śledź","szprotki"],["parówki","kiełbasa"],["kaszanka","pasztet"],["golonka","żeberka"],
["oscypek","ser żółty"],["zupa pomidorowa","ogórkowa"],["kawa","herbata"],["kompot","lemoniada"],["oranżada","cola"],
["mleko","kefir"],["jajecznica","omlet"],["owsianka","musli"],["kanapka","tost"],["banan","mango"],
["truskawki","maliny"],["arbuz","melon"],["winogrona","rodzynki"],["miód","dżem"],["ketchup","musztarda"]]},
{id:'sport',name:'Sport i ruch',words:[
["skok w dal","skok wzwyż"],["joga","pilates"],["bramkarz","napastnik"],["maraton","sprint"],["siatkówka","koszykówka"],
["piłka nożna","piłka ręczna"],["tenis","badminton"],["ping-pong","squash"],["pływanie","nurkowanie"],["narty","snowboard"],
["łyżwy","wrotki"],["hulajnoga","deskorolka"],["rower","tandem"],["siłownia","crossfit"],["pompki","przysiady"],
["brzuszki","deska"],["boks","karate"],["judo","zapasy"],["szermierka","łucznictwo"],["wspinaczka","alpinizm"],
["bieganie","nordic walking"],["skakanka","hula-hop"],["trampolina","dmuchany zamek"],["kręgle","bilard"],["rzutki","bule"],
["szachy","warcaby"],["jazda konna","rodeo"],["formuła 1","żużel"],["skoki narciarskie","biegi narciarskie"],["hokej","curling"],
["golf","minigolf"],["surfing","kitesurfing"],["kajakarstwo","wioślarstwo"],["żeglarstwo","windsurfing"],["wędkarstwo","grzybobranie"],
["taniec towarzyski","balet"],["zumba","aerobik"],["cheerleaderki","gimnastyka artystyczna"],["sumo","przeciąganie liny"],["parkour","akrobatyka"]]},
{id:'zawody',name:'Zawody',words:[
["strażak","policjant"],["fryzjer","barber"],["youtuber","influencer"],["lekarz","weterynarz"],["dentysta","ortodonta"],
["nauczyciel","przedszkolanka"],["kucharz","cukiernik"],["kelner","barman"],["pilot samolotu","stewardesa"],["kierowca autobusu","taksówkarz"],
["listonosz","kurier"],["rolnik","ogrodnik"],["górnik","hutnik"],["hydraulik","elektryk"],["mechanik","wulkanizator"],
["programista","grafik"],["księgowy","bankier"],["adwokat","notariusz"],["aktor","kaskader"],["piosenkarz","raper"],
["malarz","rzeźbiarz"],["fotograf","kamerzysta"],["dziennikarz","prezenter pogody"],["astronauta","astronom"],["naukowiec","wynalazca"],
["archeolog","paleontolog"],["detektyw","szpieg"],["ochroniarz","wykidajło"],["żołnierz","komandos"],["ksiądz","zakonnica"],
["psycholog","psychiatra"],["wróżka","jasnowidz"],["masażysta","fizjoterapeuta"],["trener personalny","dietetyk"],["modelka","stylistka"],
["sprzątaczka","pokojówka"],["kominiarz","dekarz"],["rzeźnik","piekarz"],["bibliotekarz","archiwista"],["klaun","iluzjonista"]]},
{id:'miejsca',name:'Miejsca',words:[
["plaża","basen"],["Wawel","Malbork"],["poczekalnia u dentysty","urząd skarbowy"],["kino","teatr"],["galeria handlowa","bazar"],
["biblioteka","księgarnia"],["kościół","cmentarz"],["szpital","przychodnia"],["szkoła","przedszkole"],["las","park"],
["góry","morze"],["pustynia","dżungla"],["zoo","cyrk"],["wesołe miasteczko","park wodny"],["stadion","hala sportowa"],
["lotnisko","dworzec PKP"],["przystanek autobusowy","peron"],["stacja benzynowa","myjnia samochodowa"],["Żabka","Biedronka"],["restauracja","stołówka"],
["kawiarnia","cukiernia"],["pizzeria","smażalnia ryb"],["muzeum","galeria sztuki"],["planetarium","obserwatorium"],["escape room","paintball"],
["kręgielnia","sala zabaw"],["sauna","jacuzzi"],["solarium","salon tatuażu"],["komisariat","sąd"],["więzienie","bunkier"],
["zamek","pałac"],["wieża Eiffla","Statua Wolności"],["Bałtyk","Mazury"],["Zakopane","Sopot"],["działka","kemping"],
["strych","piwnica"],["winda","schody ruchome"],["toaleta publiczna","przebieralnia"],["sala weselna","remiza"],["plac zabaw","piaskownica"]]},
{id:'filmy',name:'Filmy i bajki',words:[
["Shrek","Fiona"],["Harry Potter","Władca Pierścieni"],["Smerfy","Minionki"],["Batman","Superman"],["Spider-Man","Iron Man"],
["Kraina Lodu","Vaiana"],["Król Lew","Madagaskar"],["Toy Story","Epoka Lodowcowa"],["Kubuś Puchatek","Miś Uszatek"],["Bolek i Lolek","Reksio"],
["Kot w Butach","Garfield"],["Scooby-Doo","Psi Patrol"],["SpongeBob","Świnka Peppa"],["Pokemon","Dragon Ball"],["Gwiezdne Wojny","Star Trek"],
["Kevin sam w domu","Grinch"],["Titanic","Dirty Dancing"],["Rocky","Rambo"],["James Bond","Mission Impossible"],["Piraci z Karaibów","Indiana Jones"],
["Park Jurajski","Godzilla"],["Matrix","Incepcja"],["Avatar","Diuna"],["Terminator","RoboCop"],["Szybcy i wściekli","Taxi"],
["Gladiator","Troja"],["Kiler","Chłopaki nie płaczą"],["Sami swoi","Kogel-mogel"],["Świat według Kiepskich","Ranczo"],["Gra o tron","Wikingowie"],
["Stranger Things","Wednesday"],["Squid Game","Dom z papieru"],["Przyjaciele","Teoria wielkiego podrywu"],["Myszka Miki","Kaczor Donald"],["Tom i Jerry","Zwariowane melodie"],
["Wiedźmin","Hobbit"],["E.T.","Obcy"],["Rejs","Miś"],["Deadpool","Wolverine"],["Barbie","Oppenheimer"]]},
{id:'dom',name:'Dom i codzienność',words:[
["odkurzacz","mop"],["poniedziałek","budzik"],["korek na drodze","kolejka do kasy"],["pranie","prasowanie"],["zmywarka","zlew"],
["lodówka","zamrażarka"],["mikrofalówka","piekarnik"],["czajnik","ekspres do kawy"],["pilot od telewizora","ładowarka"],["kanapa","fotel"],
["koc","poduszka"],["kapcie","piżama"],["szlafrok","ręcznik"],["szczoteczka do zębów","nić dentystyczna"],["prysznic","wanna"],
["papier toaletowy","chusteczki"],["kosz na śmieci","segregacja śmieci"],["rachunki","podatki"],["zakupy spożywcze","lista zakupów"],["paragon","promocja"],
["sąsiad z wiertarką","pies sąsiada"],["młotek","śrubokręt"],["drabina","taboret"],["żarówka","świeczka"],["gniazdko","przedłużacz"],
["wi-fi","router"],["telefon","tablet"],["telewizor","radio"],["doniczka","konewka"],["firanki","rolety"],
["dywan","panele"],["klucze","portfel"],["parasol","kalosze"],["apteczka","termometr"],["drzemka","sjesta"],
["niedziela u babci","święta u rodziny"],["remont","przeprowadzka"],["kurz","pajęczyna"],["skarpetki nie do pary","plątanina kabli"],["weekend","urlop"]]},
{id:'podroze',name:'Podróże',words:[
["walizka","plecak"],["all inclusive","last minute"],["zgubiony bagaż","opóźniony lot"],["paszport","dowód osobisty"],["odprawa","kontrola bezpieczeństwa"],
["bilet","rezerwacja"],["hotel","hostel"],["namiot","przyczepa kempingowa"],["mapa","GPS"],["przewodnik","pilot wycieczki"],
["zwiedzanie","leżenie na plaży"],["pamiątki","magnesy na lodówkę"],["selfie z zabytkiem","zdjęcie jedzenia"],["autostop","pociąg nocny"],["rejs","prom"],
["safari","trekking"],["wycieczka autokarowa","kolonie"],["Giewont","Rysy"],["Chorwacja","Grecja"],["Egipt","Turcja"],
["Paryż","Rzym"],["Londyn","Nowy Jork"],["Majorka","Ibiza"],["city break","weekend w spa"],["pakowanie na ostatnią chwilę","nadbagaż"],
["strefa czasowa","jet lag"],["opalanie","krem z filtrem"],["klapki","okulary przeciwsłoneczne"],["strój kąpielowy","ręcznik plażowy"],["leżak","parasol plażowy"],
["gofry nad morzem","ryba z frytkami"],["deptak","molo"],["latarnia morska","port"],["muszelki","bursztyn"],["szlak górski","schronisko"],
["Kasprowy Wierch","Morskie Oko"],["wiza","szczepienia"],["kantor","bankomat"],["taksówka z lotniska","Uber"],["pocztówka","pamiątkowy kubek"]]}
];
export const ADULT = [
{id:'flirt',name:'Flirt i seks',words:[
["szybki numerek","poranny seks"],["jednonocna przygoda","wakacyjny romans"],["gra wstępna","masaż erotyczny"],["sexting","nagie zdjęcie"],["striptiz","taniec na rurze"],
["pocałunek z języczkiem","malinka"],["przyjaciele z korzyściami","romans w pracy"],["seks w samochodzie","seks na plaży"],["orgazm","udawany orgazm"],["pozycja jeźdźca","pozycja misjonarska"],
["69","doggy style"],["dirty talk","jęczenie"],["seks oralny","robienie loda"],["masturbacja","filmy dla dorosłych"],["napalenie","zimny prysznic"],
["poranny wzwód","mokry sen"],["prezerwatywa","kalendarzyk"],["stosunek przerywany","wpadka"],["trójkąt","orgia"],["swingersi","nudyści"],
["fetysz stóp","skarpetki w łóżku"],["skok w bok","zdrada"],["kochanka","ta trzecia"],["libido","testosteron"],["punkt G","łechtaczka"],
["rozmiar ma znaczenie","liczy się technika"],["gorąca linia","czat dla dorosłych"],["rozbierany poker","gra w butelkę"],["głęboki dekolt","krótka spódniczka"],["całowanie po szyi","gryzienie ucha"],
["seks po pijaku","seks na kacu"],["seks w pracy","seks w windzie"],["erotyczny sen","sen o byłej"],["sutki","piercing intymny"],["depilacja bikini","zarost na klacie"],
["pierwszy raz","seks po ślubie"],["skrzypiące łóżko","cienkie ściany"],["seks przy zgaszonym świetle","seks przy świecach"],["afrodyzjak","ostrygi"],["viagra","żeń-szeń"]]},
{id:'sypialnia',name:'Sypialnia',words:[
["wibrator","króliczek"],["kajdanki","opaska na oczy"],["bielizna erotyczna","stringi"],["kamasutra","joga"],["pejcz","szpicruta"],
["lateks","skórzany strój"],["gadżety erotyczne","sex shop"],["lubrykant","olejek do masażu"],["kostium pielęgniarki","kostium pokojówki"],["podwiązki","pończochy"],
["gorset","body"],["jedwabna pościel","świece zapachowe"],["lustro na suficie","okrągłe łóżko"],["klapsy","pociąganie za włosy"],["dominacja","uległość"],
["odgrywanie ról","przebieranki"],["bezpieczne słowo","hasło do wi-fi"],["wieczór panieński","wieczór kawalerski"],["striptizer","striptizerka"],["taniec erotyczny","taniec brzucha"],
["przyciemnione światło","czerwona żarówka"],["playlista do seksu","saksofon"],["szeptanie do ucha","oddech na karku"],["masaż tantryczny","masaż happy end"],["prezerwatywy smakowe","jadalna bielizna"],
["bita śmietana","sos czekoladowy"],["truskawki i szampan","śniadanie do łóżka"],["jajeczko z pilotem","zabawka sterowana aplikacją"],["korek analny","kulki gejszy"],["nagie selfie","zdjęcie w ręczniku"],
["maraton w łóżku","przerwa na pizzę"],["kości erotyczne","karty z pozycjami"],["prysznic we dwoje","wspólna kąpiel"],["rozrzucone ubrania","urwane guziki"],["zasłonięte okna","drzwi zamknięte na klucz"],
["\u201enie dziś, boli mnie głowa\u201d","\u201ejestem zmęczony\u201d"],["połamane łóżko","ślady na plecach"],["zadrapania","ugryzienia"],["hotel na godziny","pokój z jacuzzi"],["sekretna szuflada","pudełko pod łóżkiem"]]},
{id:'randki',name:'Randki i podryw',words:[
["Tinder","Badoo"],["ghosting","friendzone"],["randka w ciemno","speed dating"],["sugar daddy","sponsor"],["walk of shame","powrót o świcie"],
["podryw na siłowni","podryw w klubie"],["tekst na podryw","\u201eskądś cię znam\u201d"],["pierwsza randka","spotkanie z rodzicami"],["kolacja przy świecach","Netflix i chill"],["pisanie do byłej","stalkowanie eks na Insta"],
["swipe w prawo","superlajk"],["catfishing","filtry na zdjęciach"],["love bombing","miłość od pierwszego wejrzenia"],["czerwone flagi","zielone flagi"],["situationship","\u201eto skomplikowane\u201d"],
["flirt z barmanem","napiwek z numerem telefonu"],["numer na serwetce","DM na Instagramie"],["podryw na psa","podryw na gitarę"],["\u201eu mnie czy u ciebie?\u201d","\u201epokażę ci kolekcję winyli\u201d"],["zasada trzeciej randki","całowanie na pierwszej randce"],
["dzielenie rachunku","kto płaci za kolację"],["spóźnienie na randkę","odwołanie w ostatniej chwili"],["randka z koszmaru","ucieczka przez okno w toalecie"],["piąte koło u wozu","przyzwoitka"],["seryjny randkowicz","wieczny kawaler"],
["SMS \u201eśpisz?\u201d","\u201eco robisz?\u201d o północy"],["zazdrość o lajki","sprawdzanie obserwujących"],["oficjalny status","\u201eto nic poważnego\u201d"],["pierwszy pocałunek","niezręczny uścisk"],["crush na baristę","flirt z kurierem"],
["randka w McDonaldzie","romantyczny kebab"],["wspólne zdjęcie profilowe","ogłoszenie związku na fejsie"],["rocznica","walentynki"],["bukiet róż","pluszowy miś"],["serenada pod oknem","wiersz miłosny"],
["podwójna randka","swatanie przez znajomych"],["miłość z odzysku","powrót do eks"],["toksyczny związek","związek on-off"],["wysyłanie serduszek","lajk na starym zdjęciu"],["oświadczyny w restauracji","ślub w Vegas"]]},
{id:'melanz',name:'Melanż i używki',words:[
["kac gigant","kac moralny"],["shoty","tequila z solą"],["urwany film","\u201ejak ja wróciłem do domu?\u201d"],["zgon na kanapie","spanie w wannie"],["melanż do rana","nieplanowana domówka"],
["before","wyjście na jednego"],["zimne piwko","ciepła wódka"],["jägerbomb","wódka z energetykiem"],["beer pong","flanki"],["wznoszenie toastu","przemowa wujka na weselu"],
["drink z palemką","piña colada"],["wino w kartonie","najtańsze wino z Żabki"],["bimber","nalewka babci"],["kufel piwa","lampka wina"],["degustacja wina","wąchanie korka"],
["szlugi pod klubem","dymek na balkonie"],["vape","fajka wodna"],["zioło","skręt"],["szampan","prosecco"],["otwieranie piwa zapalniczką","otwieranie zębami"],
["karaoke po pijaku","śpiewanie w taksówce"],["prośby do DJ-a","\u201epuść coś z Disco Polo\u201d"],["procenty","promile"],["kontrola trzeźwości","dmuchanie w alkomat"],["taxi o 4 rano","nocny autobus"],
["kebab o 3 w nocy","zapiekanka po imprezie"],["jajecznica na kacu","rosołek ratunkowy"],["sok z kiszonych ogórków","elektrolity"],["\u201eostatni i idziemy\u201d","\u201ejeszcze jedna kolejka\u201d"],["dzwonienie po pijaku","pijackie SMS-y"],
["zgubiony telefon","zgubione klucze"],["przewrotka na parkiecie","taniec z krzesłem"],["barman zna cię po imieniu","stały bywalec"],["happy hours","dwa w cenie jednego"],["selekcjoner pod klubem","lista VIP"],
["szatnia w klubie","zgubiony numerek"],["impreza w plenerze","domówka"],["sylwester","andrzejki"],["wesele","poprawiny"],["\u201enigdy więcej alkoholu\u201d","\u201eod poniedziałku nie piję\u201d"]]},
{id:'wstyd',name:'Wstyd i wpadki',words:[
["SMS do byłej o 3 w nocy","telefon do eks po winie"],["taniec na stole","upadek ze stołu"],["wpadka przy teściach","przypał na rodzinnym obiedzie"],["rozpięty rozporek","szpinak w zębach"],["pomylenie imion w łóżku","nazwanie szefa \u201emamo\u201d"],
["pierdnięcie na jodze","beknięcie na randce"],["wiadomość do złej osoby","screenshot wysłany do osoby ze screenshota"],["lajk podczas stalkowania","konto do podglądania"],["papier toaletowy u buta","sweter na lewą stronę"],["pomachanie do nieznajomego","piątka w pustkę"],
["potknięcie na oczach tłumu","udawany podbieg"],["\u201etobie też smacznego\u201d do kelnera","\u201ewzajemnie\u201d do kasjerki"],["chrapanie na spotkaniu","zaśnięcie w kinie"],["odsłuchanie własnego głosu","nagranie wysłane za wcześnie"],["pomylenie sal","wejście na złe zebranie na Zoomie"],
["niewyciszony mikrofon","kamerka włączona za wcześnie"],["przeproszenie manekina","rozmowa z automatem"],["pchanie drzwi \u201eciągnij\u201d","ciągnięcie drzwi \u201epchaj\u201d"],["pęknięte spodnie w kroku","dziura w skarpecie u znajomych"],["zapomniany portfel na randce","odrzucona karta przy kolacji"],
["bąk w windzie","czkawka na pogrzebie"],["śpiewanie złego tekstu","fałszowanie na karaoke"],["\u201eto który miesiąc?\u201d","niezręczne gratulacje"],["CV z literówką","mail podpisany \u201ecałuję\u201d"],["\u201ekocham cię\u201d za wcześnie","\u201ekocham cię\u201d do kumpla"],
["wyjście z domu w kapciach","piżama w Biedronce"],["mokra plama na spodniach","\u201eto tylko woda!\u201d"],["zapomniane życzenia","\u201esto lat\u201d nie w tym momencie"],["telefon w kościele","dzwonek w teatrze"],["niezręczne przywitanie","pocałunek w powietrze"],
["dwa razy \u201ecześć\u201d do tej samej osoby","przedstawianie się znajomemu"],["zgubiony wątek opowieści","pointa, która nie siadła"],["śmiech w złym momencie","parsknięcie na minucie ciszy"],["cebula przed randką","czosnkowy oddech"],["pot pod pachami","mokry uścisk dłoni"],
["wejście w szybę","machanie do własnego odbicia"],["autokorekta w najgorszym momencie","dyktowanie głosowe w tramwaju"],["oczko w rajstopach","guzik, który odpadł"],["śpiewanie na głos w słuchawkach","za głośna muzyka w słuchawkach"],["zapomniany PIN przy kasie","płacenie drobniakami w kolejce"]]},
{id:'slownik',name:'Mocny słownik',words:[
["kurwa","cholera jasna"],["chuj","fiut"],["dupa","tyłek"],["zajebiście","mega"],["pierdolić","pieprzyć"],
["spierdalaj","spadaj"],["jebnięty","walnięty"],["cipka","muszelka"],["cycki","balony"],["dupek","palant"],
["skurwysyn","sukinsyn"],["gówno","kupa"],["zesrać się ze śmiechu","posikać się ze śmiechu"],["wkurwiony","wściekły"],["ochujeć","zbaranieć"],
["przypał","obciach"],["beka","heheszki"],["dzban","leszcz"],["laska","ciacho"],["zaliczyć","przelecieć"],
["ruchać","bzykać"],["obciąganie","dmuchanie"],["walić konia","trzepać kapucyna"],["kutas","wacek"],["jaja","klejnoty rodowe"],
["napalony","nagrzany"],["dymanko","łóżkowe akrobacje"],["gołe baby","świerszczyki"],["burdel","bajzel"],["kurwiki w oczach","diabelski uśmiech"],
["zjebać","spartaczyć"],["najebany","nawalony"],["zryty beret","odklejka"],["mieć wyjebane","mieć gdzieś"],["pocałuj mnie w dupę","wypchaj się"],
["gówniana robota","czarna robota"],["jebut","łubudu"],["do dupy","do kitu"],["sranie w banię","mydlenie oczu"],["chujnia","lipa"]]}
];
