// Baza haseł IMPOSTOR — pary [hasło, bliźniak] do wariantu "bliźniacze hasło".
// W trybie zwykłym losowana jest jedna strona pary.
export const FAMILY = [
{id:'zwierzeta',name:'Zwierzęta',words:[
["żyrafa","struś"],["pingwin","foka"],["jeż","kret"],["słoń","mamut"],["kot","pies"],
["chomik","świnka morska"],["papuga","kanarek"],["rekin","delfin"],["żółw","ślimak"],["lew","tygrys"],
["wilk","lis"],["niedźwiedź","łoś"],["koń","osioł"],["krowa","koza"],["kura","kaczka"],
["sowa","nietoperz"],["pszczoła","osa"],["komar","mucha"],["pająk","skorpion"],["wąż","jaszczurka"],
["żaba","ropucha"],["bocian","żuraw"],["wiewiórka","szop pracz"],["mrówka","żuk"],["motyl","ćma"],
["orzeł","sokół"],["flaming","paw"],["wielbłąd","lama"],["kangur","koala"],["małpa","goryl"],
["krokodyl","aligator"],["hipopotam","nosorożec"],["zebra","antylopa"],["panda","leniwiec"],["jednorożec","pegaz"],
["dinozaur","smok"],["złota rybka","karp"],["homar","krab"],["ośmiornica","meduza"],["jamnik","mops"]]},
{id:'jedzenie',name:'Jedzenie',words:[
["pierogi","uszka"],["pizza hawajska","zapiekanka"],["żurek","barszcz biały"],["kebab","gyros"],["schabowy","kotlet mielony"],
["bigos","kapuśniak"],["rosół","krupnik"],["naleśniki","racuchy"],["placki ziemniaczane","pyzy"],["spaghetti","lasagne"],
["sushi","ramen"],["hamburger","hot dog"],["frytki","chipsy"],["lody","sorbet"],["sernik","szarlotka"],
["pączek","drożdżówka"],["gofry","churros"],["czekolada","krem czekoladowy"],["żelki","guma do żucia"],["popcorn","nachosy"],
["ogórek kiszony","kapusta kiszona"],["śledź","szprotki"],["parówki","kiełbasa"],["kaszanka","pasztet"],["golonka","żeberka"],
["oscypek","ser żółty"],["zupa pomidorowa","ogórkowa"],["kawa","herbata"],["kompot","lemoniada"],["oranżada","cola"],
["mleko","kefir"],["jajecznica","omlet"],["owsianka","musli"],["kanapka","tost"],["banan","mango"],
["truskawki","maliny"],["arbuz","melon"],["winogrona","rodzynki"],["miód","dżem"],["ketchup","musztarda"]]},
{id:'sport',name:'Sport i ruch',words:[
["skok w dal","skok wzwyż"],["joga","pilates"],["bramkarz","napastnik"],["maraton","sprint"],["siatkówka","koszykówka"],
["piłka nożna","piłka ręczna"],["tenis","badminton"],["ping-pong","squash"],["pływanie","nurkowanie"],["narty","snowboard"],
["łyżwy","wrotki"],["hulajnoga","deskorolka"],["rower","tandem"],["siłownia","crossfit"],["pompki","przysiady"],
["brzuszki","deska"],["boks","karate"],["judo","zapasy"],["szermierka","łucznictwo"],["wspinaczka","alpinizm"],
["bieganie","nordic walking"],["skakanka","hula-hop"],["trampolina","dmuchany zamek"],["kręgle","bilard"],["rzutki","bule"],
["szachy","warcaby"],["jazda konna","rodeo"],["formuła 1","żużel"],["skoki narciarskie","biegi narciarskie"],["hokej","curling"],
["golf","minigolf"],["surfing","kitesurfing"],["kajakarstwo","wioślarstwo"],["żeglarstwo","windsurfing"],["wędkarstwo","grzybobranie"],
["taniec towarzyski","balet"],["zumba","aerobik"],["cheerleaderki","gimnastyka artystyczna"],["sumo","przeciąganie liny"],["parkour","akrobatyka"]]},
{id:'zawody',name:'Zawody',words:[
["strażak","policjant"],["fryzjer","barber"],["youtuber","influencer"],["lekarz","weterynarz"],["dentysta","ortodonta"],
["nauczyciel","przedszkolanka"],["kucharz","cukiernik"],["kelner","barman"],["pilot samolotu","stewardesa"],["kierowca autobusu","taksówkarz"],
["listonosz","kurier"],["rolnik","ogrodnik"],["górnik","hutnik"],["hydraulik","elektryk"],["mechanik","wulkanizator"],
["programista","grafik"],["księgowy","bankier"],["adwokat","notariusz"],["aktor","kaskader"],["piosenkarz","raper"],
["malarz","rzeźbiarz"],["fotograf","kamerzysta"],["dziennikarz","prezenter pogody"],["astronauta","astronom"],["naukowiec","wynalazca"],
["archeolog","paleontolog"],["detektyw","szpieg"],["ochroniarz","wykidajło"],["żołnierz","komandos"],["ksiądz","zakonnica"],
["psycholog","psychiatra"],["wróżka","jasnowidz"],["masażysta","fizjoterapeuta"],["trener personalny","dietetyk"],["modelka","stylistka"],
["sprzątaczka","pokojówka"],["kominiarz","dekarz"],["rzeźnik","piekarz"],["bibliotekarz","archiwista"],["klaun","iluzjonista"]]},
{id:'miejsca',name:'Miejsca',words:[
["plaża","basen"],["Wawel","Malbork"],["poczekalnia u dentysty","urząd skarbowy"],["kino","teatr"],["galeria handlowa","bazar"],
["biblioteka","księgarnia"],["kościół","cmentarz"],["szpital","przychodnia"],["szkoła","przedszkole"],["las","park"],
["góry","morze"],["pustynia","dżungla"],["zoo","cyrk"],["wesołe miasteczko","park wodny"],["stadion","hala sportowa"],
["lotnisko","dworzec PKP"],["przystanek autobusowy","peron"],["stacja benzynowa","myjnia samochodowa"],["Żabka","Biedronka"],["restauracja","stołówka"],
["kawiarnia","cukiernia"],["pizzeria","smażalnia ryb"],["muzeum","galeria sztuki"],["planetarium","obserwatorium"],["escape room","paintball"],
["kręgielnia","sala zabaw"],["sauna","jacuzzi"],["solarium","salon tatuażu"],["komisariat","sąd"],["więzienie","bunkier"],
["zamek","pałac"],["wieża Eiffla","Statua Wolności"],["Bałtyk","Mazury"],["Zakopane","Sopot"],["działka","kemping"],
["strych","piwnica"],["winda","schody ruchome"],["toaleta publiczna","przebieralnia"],["sala weselna","remiza"],["plac zabaw","piaskownica"]]},
{id:'filmy',name:'Filmy i bajki',words:[
["Shrek","Fiona"],["Harry Potter","Władca Pierścieni"],["Smerfy","Minionki"],["Batman","Superman"],["Spider-Man","Iron Man"],
["Kraina Lodu","Vaiana"],["Król Lew","Madagaskar"],["Toy Story","Epoka Lodowcowa"],["Kubuś Puchatek","Miś Uszatek"],["Bolek i Lolek","Reksio"],
["Kot w Butach","Garfield"],["Scooby-Doo","Psi Patrol"],["SpongeBob","Świnka Peppa"],["Pokemon","Dragon Ball"],["Gwiezdne Wojny","Star Trek"],
["Kevin sam w domu","Grinch"],["Titanic","Dirty Dancing"],["Rocky","Rambo"],["James Bond","Mission Impossible"],["Piraci z Karaibów","Indiana Jones"],
["Park Jurajski","Godzilla"],["Matrix","Incepcja"],["Avatar","Diuna"],["Terminator","RoboCop"],["Szybcy i wściekli","Taxi"],
["Gladiator","Troja"],["Kiler","Chłopaki nie płaczą"],["Sami swoi","Kogel-mogel"],["Świat według Kiepskich","Ranczo"],["Gra o tron","Wikingowie"],
["Stranger Things","Wednesday"],["Squid Game","Dom z papieru"],["Przyjaciele","Teoria wielkiego podrywu"],["Myszka Miki","Kaczor Donald"],["Tom i Jerry","Zwariowane melodie"],
["Wiedźmin","Hobbit"],["E.T.","Obcy"],["Rejs","Miś"],["Deadpool","Wolverine"],["Barbie","Oppenheimer"]]},
{id:'dom',name:'Dom i codzienność',words:[
["odkurzacz","mop"],["poniedziałek","budzik"],["korek na drodze","kolejka do kasy"],["pranie","prasowanie"],["zmywarka","zlew"],
["lodówka","zamrażarka"],["mikrofalówka","piekarnik"],["czajnik","ekspres do kawy"],["pilot od telewizora","ładowarka"],["kanapa","fotel"],
["koc","poduszka"],["kapcie","piżama"],["szlafrok","ręcznik"],["szczoteczka do zębów","nić dentystyczna"],["prysznic","wanna"],
["papier toaletowy","chusteczki"],["kosz na śmieci","segregacja śmieci"],["rachunki","podatki"],["zakupy spożywcze","lista zakupów"],["paragon","promocja"],
["sąsiad z wiertarką","pies sąsiada"],["młotek","śrubokręt"],["drabina","taboret"],["żarówka","świeczka"],["gniazdko","przedłużacz"],
["wi-fi","router"],["telefon","tablet"],["telewizor","radio"],["doniczka","konewka"],["firanki","rolety"],
["dywan","panele"],["klucze","portfel"],["parasol","kalosze"],["apteczka","termometr"],["drzemka","sjesta"],
["niedziela u babci","święta u rodziny"],["remont","przeprowadzka"],["kurz","pajęczyna"],["skarpetki nie do pary","plątanina kabli"],["weekend","urlop"]]},
{id:'podroze',name:'Podróże',words:[
["walizka","plecak"],["all inclusive","last minute"],["zgubiony bagaż","opóźniony lot"],["paszport","dowód osobisty"],["odprawa","kontrola bezpieczeństwa"],
["bilet","rezerwacja"],["hotel","hostel"],["namiot","przyczepa kempingowa"],["mapa","GPS"],["przewodnik","pilot wycieczki"],
["zwiedzanie","leżenie na plaży"],["pamiątki","magnesy na lodówkę"],["selfie z zabytkiem","zdjęcie jedzenia"],["autostop","pociąg nocny"],["rejs","prom"],
["safari","trekking"],["wycieczka autokarowa","kolonie"],["Giewont","Rysy"],["Chorwacja","Grecja"],["Egipt","Turcja"],
["Paryż","Rzym"],["Londyn","Nowy Jork"],["Majorka","Ibiza"],["city break","weekend w spa"],["pakowanie na ostatnią chwilę","nadbagaż"],
["strefa czasowa","jet lag"],["opalanie","krem z filtrem"],["klapki","okulary przeciwsłoneczne"],["strój kąpielowy","ręcznik plażowy"],["leżak","parasol plażowy"],
["gofry nad morzem","ryba z frytkami"],["deptak","molo"],["latarnia morska","port"],["muszelki","bursztyn"],["szlak górski","schronisko"],
["Kasprowy Wierch","Morskie Oko"],["wiza","szczepienia"],["kantor","bankomat"],["taksówka z lotniska","Uber"],["pocztówka","pamiątkowy kubek"]]}
];
export const ADULT = [
{id:'flirt',name:'Flirt i seks',words:[
["szybki numerek","poranne ruchanko"],["jednonocna przygoda","wyrwanie kogoś na melanżu"],["gra wstępna","palcówka"],["sexting","dick pic"],
["striptiz","taniec na rurze"],["malinka","ssanie szyi"],["przyjaciele z korzyściami","stały bzykacz"],["seks w samochodzie","seks na masce auta"],
["orgazm","udawany orgazm"],["pozycja na jeźdźca","odwrócona amazonka"],["69","na pieska"],["dirty talk","głośne jęczenie"],
["robienie loda","głębokie gardło"],["walenie konia","masturbacja pod prysznicem"],["napalenie","chcica"],["poranny wzwód","mokry sen"],
["seks bez gumki","stosunek przerywany"],["wytrysk","spust"],["trójkąt","orgia"],["swingersi","wymiana partnerów"],
["fetysz stóp","lizanie palców u nóg"],["skok w bok","ruchanie na boku"],["kochanka","ta trzecia"],["punkt G","łechtaczka"],
["mokra cipka","ciasna cipka"],["rozbierany poker","butelka na rozbieranie"],["głęboki dekolt","prześwitująca bluzka"],["całowanie po szyi","gryzienie ucha"],
["seks po pijaku","seks na kacu"],["seks w windzie","seks w toalecie klubu"],["wytrysk na twarz","wytrysk na cycki"],["sutki","piercing intymny"],
["depilacja bikini","gładka cipka"],["pierwszy raz","rozdziewiczenie"],["skrzypiące łóżko","cienkie ściany"],["seks przy lustrze","ruchanie przy świecach"],
["afrodyzjak","ostrygi"],["viagra","wzwód na tabletce"],["seks analny","wejście od tyłu"],["seks podczas okresu","krew na prześcieradle"],
["gang bang","bukkake"],["squirting","tryskający orgazm"],["rimming","lizanie od tyłu"],["fisting","cała dłoń w akcji"],
["złoty deszcz","zabawy z sikaniem"],["pegging","strap-on"],["BDSM","sado-maso"],["dominatrix","sesja u pani dominy"],
["OnlyFans","kamerki dla dorosłych"],["agencja towarzyska","dziewczyna na telefon"]
]},
{id:'sypialnia',name:'Sypialnia',words:[
["wibrator","króliczek"],["kajdanki","opaska na oczy"],["stringi","bielizna erotyczna"],["kamasutra","karty z pozycjami"],
["pejcz","szpicruta"],["lateks","skórzane wdzianko"],["gadżety erotyczne","sex shop"],["lubrykant","olejek do masażu"],
["kostium pielęgniarki","kostium pokojówki"],["podwiązki","kabaretki"],["gorset","koronkowe body"],["klapsy","pociąganie za włosy"],
["dominacja","uległość"],["odgrywanie ról","przebieranki w łóżku"],["bezpieczne słowo","szyfr na seks"],["striptizer","striptizerka"],
["taniec erotyczny","lap dance"],["masaż tantryczny","masaż z happy endem"],["prezerwatywy smakowe","jadalna bielizna"],["bita śmietana na sutkach","czekolada na brzuchu"],
["wibrujące jajeczko","zabawka na pilota"],["korek analny","kulki gejszy"],["nagie selfie","fotka spod prysznica"],["maraton seksu","runda druga"],
["seks pod prysznicem","wspólna kąpiel z pianą"],["rozrzucone ubrania","urwane guziki"],["ślady paznokci na plecach","zadrapania"],["klaps w tyłek","ugryzienie w pośladek"],
["hotel na godziny","pokój z jacuzzi"],["sekretna szuflada","pudełko pod łóżkiem"],["lustro na suficie","okrągłe łóżko"],["połamane łóżko","sąsiedzi walący w ścianę"],
["sekstaśma","domowe porno"],["nagrywanie się w łóżku","kamerka w sypialni"],["gorący wosk","kostki lodu"],["krępowanie szarfą","wiązanie do łóżka"],
["kości erotyczne","gra w rozbieranego"],["mokre prześcieradło","plama na pościeli"],["tort w kształcie penisa","balony w kształcie penisa"],["seks od rana","numerek przed pracą"],
["huśtawka erotyczna","krzyż świętego Andrzeja"],["zaciski na sutki","elektrostymulacja"],["knebel kulkowy","obroża ze smyczą"],["uprząż","liny do shibari"],
["czerwony pokój","loch rozkoszy"],["gorące lizanie lodów","banan w roli głównej"]
]},
{id:'randki',name:'Randki i podryw',words:[
["Tinder","Badoo"],["ghosting","friendzone"],["randka w ciemno","speed dating"],["sugar daddy","utrzymanka"],
["walk of shame","powrót o świcie w sukience z wczoraj"],["podryw na siłowni","podryw w klubie"],["tekst na podryw","skądś cię znam"],["Netflix i chill","chodź obejrzymy film"],
["pisanie do byłej po pijaku","stalkowanie eks na Insta"],["swipe w prawo","superlajk"],["catfishing","zdjęcie sprzed dziesięciu lat"],["czerwone flagi","zielone flagi"],
["situationship","to skomplikowane"],["flirt z barmanką","numer na serwetce"],["dick pic bez pytania","fotka klaty w lustrze"],["podryw na psa","podryw na gitarę"],
["u mnie czy u ciebie","pokażę ci mieszkanie"],["seks na pierwszej randce","zasada trzeciej randki"],["dzielenie rachunku","ucieczka przed rachunkiem"],["randka z koszmaru","ucieczka przez okno w toalecie"],
["seryjny randkowicz","wieczny singiel"],["SMS śpisz? o 2 w nocy","co robisz? o północy"],["booty call","telefon po numerek"],["przygoda z wesela","romans z druhną"],
["oficjalny status","to nic poważnego"],["pocałunek z językiem","obściskiwanie w bramie"],["randka w McDonaldzie","romantyczny kebab"],["rocznica","walentynki w motelu"],
["seks z eks","powrót do byłej"],["toksyczny związek","związek on-off"],["zdrada na wyjeździe","co było w Vegas zostaje w Vegas"],["podryw na horoskop","jaki masz znak zodiaku"],
["szybka akcja w klubie","obmacywanie na parkiecie"],["makijaż z wczoraj","niedopięta koszula rano"],["śniadanie po nocy","taxi o świcie"],["rodzice wracają wcześniej","teściowa w drzwiach"],
["seks w przymierzalni","numerek w kinie"],["podwójna randka","swatanie przez znajomych"],["oświadczyny po pijaku","ślub w Vegas"],["wyślij coś milszego","nagie zdjęcie na zachętę"]
]},
{id:'melanz',name:'Melanż i używki',words:[
["kac gigant","kac moralny"],["shoty","tequila z solą"],["urwany film","jak ja wróciłem do domu"],["zgon na kanapie","spanie w wannie"],
["melanż do rana","afterek u nieznajomych"],["before","wyjście na jednego"],["jägerbomb","wódka z energetykiem"],["beer pong","flanki"],
["drink z palemką","sex on the beach"],["wino w kartonie","najtańsza wódka z Żabki"],["bimber","nalewka babci"],["szlugi pod klubem","dymek na balkonie"],
["zioło","skręt"],["karaoke po pijaku","śpiewanie w taksówce"],["taniec na stole","striptiz na barze"],["kebab o 3 w nocy","zapiekanka po imprezie"],
["jajecznica na kacu","sok z kiszonych ogórków"],["ostatni i idziemy","jeszcze jedna kolejka"],["dzwonienie po pijaku","pijackie SMS-y do byłej"],["zgubiony telefon","zgubione majtki"],
["przewrotka na parkiecie","taniec z krzesłem"],["barman zna cię po imieniu","stały bywalec mordowni"],["selekcjoner pod klubem","wpisanie na listę"],["szatnia w klubie","zgubiony numerek"],
["sylwester","andrzejki"],["wesele","poprawiny"],["nigdy więcej alkoholu","od poniedziałku nie piję"],["sikanie za krzakiem","kolejka do toi toia"],
["paw na chodniku","rzyganie do kwietnika"],["budzenie się obok nieznajomej osoby","cudza sypialnia rano"],["seks w klubowej toalecie","obściskiwanie przy barze"],["kąpiel nago w jeziorze","skok do basenu w ubraniu"],
["promile","dmuchanie w alkomat"],["taxi o 4 rano","nocny autobus wstydu"],["domówka wymknięta spod kontroli","policja na imprezie"],["nigdy przenigdy","prawda czy wyzwanie po wódce"],
["body shots","shot z pępka"],["mokra koszulka","drink wylany na dekolt"],["toples na stole","stanik na żyrandolu"],["wpadnięcie w krzaki","spanie na trawniku"]
]},
{id:'wstyd',name:'Wstyd i wpadki',words:[
["pierdnięcie podczas seksu","pierdnięcie przy pozycji na pieska"],["pomylenie imienia w łóżku","krzyknięcie imienia byłej"],["rodzice wchodzą podczas seksu","współlokator w złym momencie"],["wibrator znaleziony przez mamę","kajdanki bez kluczyka"],
["nagie zdjęcie na grupę rodzinną","dick pic do szefowej"],["skurcz łydki w trakcie","łokieć w twarz"],["spadnięcie z łóżka","połamane łóżko u rodziców"],["malinka przed spotkaniem z teściami","ślady na plecach przed basenem"],
["jęki słyszane przez sąsiadów","walenie w ścianę od sąsiada"],["skończyłem za szybko","udawałam"],["wzwód w najgorszym momencie","brak wzwodu po wódce"],["porno niewyciszone","historia przeglądarki na wspólnym komputerze"],
["stanik zgubiony na imprezie","majtki w kieszeni kurtki"],["prezerwatywa po terminie","pusta paczka gum w szufladzie"],["sprośny SMS do złej osoby","autokorekta w sekstingu"],["plama na spodniach po randce","mokra plama na jego dżinsach"],
["pocałunek z byłą najlepszego kumpla","obudzenie się obok kolegi z pracy"],["czkawka podczas seksu","kichnięcie w trakcie"],["telefon od mamy w trakcie seksu","budzik w złym momencie"],["rozdarte rajstopy","guzik który odstrzelił"],
["seks na plaży i piasek wszędzie","seks w lesie i komary"],["upadek przy zdejmowaniu spodni","skarpetki do samego końca"],["kocham cię w trakcie seksu","płacz po seksie"],["burczenie w brzuchu na randce","beknięcie przy pocałunku"],
["zapomniane imię rano","zapisana jako Tinder Kaśka 3"],["szampon w oczach pod wspólnym prysznicem","zimna woda w romantycznej kąpieli"],["seksowny taniec zakończony upadkiem","rura która się obluzowała"],["screen wysłany do osoby ze screena","pochwalenie się nie temu koledze"],
["niewyciszony mikrofon przy sprośnej rozmowie","kamerka włączona w złym momencie"],["stringi na wizytę u lekarza","seksowna bielizna na złą okazję"],["flirt z zajętą osobą","podryw na oczach jej chłopaka"],["kac przerywający poranne figle","przerwa na wymioty w trakcie randki"],
["sprośny sen o koledze z pracy","rumieniec na porannym zebraniu"],["romans ujawniony na firmowej wigilii","flirt z kadrową przy ksero"],["striptiz w złym oknie","sąsiad z lornetką"],["paragon z sex shopu w portfelu","znajoma kasjerka przy zakupie gadżetów"],
["alarm w hotelu na godziny","ewakuacja w samym szlafroku"],["kocham cię wysłane do szefa","serduszko do klientki"],["przyłapanie na masturbacji","drzwi bez zamka"],["jęk z telefonu w autobusie","porno na rzutniku w pracy"]
]},
{id:'slownik',name:'Mocny słownik',words:[
["kurwa","kurwa mać"],["chuj","kutas"],["dupa","dupsko"],["zajebiście","zajebiaszczo"],
["pierdolić","jebać"],["spierdalaj","wypierdalaj"],["jebnięty","pojebany"],["cipka","pizda"],
["cycki","cyce"],["dupek","chujek"],["skurwysyn","skurwiel"],["gówno","gówno prawda"],
["zesrać się","obesrać się"],["wkurwiony","rozjebany"],["ochujeć","zjebać się"],["do dupy","do chuja"],
["jebać biedę","chuj z tym"],["stary pierdziel","zgred"],["laska","dupencja"],["zaliczyć","przelecieć"],
["ruchać","bzykać"],["obciąganie","dmuchanie"],["walić konia","trzepać gruchę"],["jaja","klejnoty rodowe"],
["napalony","nagrzany"],["dymanko","posuwanko"],["świerszczyki","pornosy"],["burdel","bajzel"],
["zjebać","spierdolić"],["najebany","nawalony"],["zryty beret","odklejka"],["mieć wyjebane","mieć wywalone"],
["pocałuj mnie w dupę","cmoknij mnie w rzyć"],["chujnia","chujoza"],["jebać to","pierdolić to"],["jebut","pierdut"],
["kurwiki w oczach","ruja"],["pierdolnik","syf"],["co jest kurwa","o chuj chodzi"],["fiut","wacek"]
]}
];
